### PR TITLE
Update To 0.14.1

### PR DESCRIPTION
**Pull request by TheDeibo**
(Tested on my devices)
This supplies a update ONLY TO 0.14.1

### CODE REVIEW

**Comment by TheDeibo** [comment]
Me being me, ive realised ( after being reminded my staff ) that its not released for ios or android yet, so I think this should just be realised as WIN10 Only at the moment.

Feel free to boo at me.

**Comment by robske110** [comment]
Just got released fir iOS and Android

**Comment by robske110** [comment]
image

**Comment by robske110** [comment]
Now Squash and Merge is availible!
There will be no merge commit and your two commits will be squashed into one.

**Comment by TheDeibo** [comment]
Okay. Well, at least now I can rest easily saying I tried to help. :3

**Comment by PEMapModder** [comment]
@robske110 no merge commit is only true when there are no commits on the master branch since the pull request head branch was diverged.

And, there are protocol changes in the new MCPE version. You shouldn't say that you support the new versions without actually supporting the changes.

**Comment by TheDeibo** [comment]
so is it protocol 47, not 46? If so, then my bad.

(I know as a fact that tiny mistakes cause big consequences)

**Comment by robske110** [comment]
This works 100% https://github.com/ClearSkyTeam/ClearSky/commit/18c1f64091b91822b85961c7da0bb2ec3ea7bd4d

**Comment by TheDeibo** [comment]
Well, only two way to find out if it works. 

If anyone is willing to try it out then http://pmt.mcpe.me/pmb/dl/pr:4113.phar

But another way to find out if it works, is to look at the facts. ( since I dont know where the facts are, use that full at your own risk.

(just going to remind anyone who uses that link)

> This pull request may not have been merged into the PocketMine repo.
> This means, unless you trust the pusher very much, or you know that the changes in this pull request are safe, don't download this build.
> This pull request may or may not has been approved or rejected by the PocketMine Team.

**Comment by jingz2007** [comment]
I tried the phar. It crashes RacLibInterface. Here is the important line: `[16:25:35] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed`
 Here is the full startup log because I know someone will ask: `[16:25:32] [Server thread/INFO]: Loading pocketmine.yml...
[16:25:32] [Server thread/INFO]: Loading server properties...
[16:25:32] [Server thread/INFO]: Selected English (eng) as the base language
[16:25:32] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.1 alpha
[16:25:32] [Server thread/INFO]: Starting remote control listener

Warning: socket_bind(): unable to bind address [98]: Address already in use in phar:///home/pi/pocketmine/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php on line 56
[16:25:32] [Server thread/CRITICAL]: RCON can't be started: Address already in use
[16:25:32] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[16:25:32] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
[16:25:32] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[16:25:33] [Server thread/INFO]: Loading recipes...
[16:25:34] [Server thread/ERROR]: Could not load plugin 'PocketDockConsole': Incompatible API version
[16:25:34] [Server thread/ERROR]: Could not load plugin 'SimpleAuth': Incompatible API version
[16:25:34] [Server thread/ERROR]: Could not load plugin 'CustomAreas': Incompatible API version
[16:25:34] [Server thread/INFO]: Loading TimeCommander v2.1
[16:25:34] [Server thread/INFO]: Loading Lightning_Strike v2
[16:25:34] [Server thread/INFO]: [Lightning_Strike] Preparing For StartUp... STAND BY
[16:25:34] [Server thread/INFO]: Loading PurePerms v1.3.6
[16:25:34] [Server thread/NOTICE]: PurePerms by 64FF00 (Twitter: @64FF00)

  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 

[16:25:34] [RakLibServer thread/CRITICAL]: **** FAILED TO BIND TO 0.0.0.0:19132!
[16:25:34] [RakLibServer thread/CRITICAL]: Perhaps a server is already running on that port?
[16:25:34] [Server thread/EMERGENCY]: RakLib crashed!
[16:25:34] [Server thread/INFO]: [PurePerms] Setting default language to 'en'
[16:25:34] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled.
[16:25:34] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
[16:25:34] [Server thread/INFO]: Loading PureChat v1.4.0
[16:25:34] [Server thread/INFO]: Preparing level "world"
[16:25:34] [Server thread/INFO]: Enabling TimeCommander v2.1

Warning: yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 7, column 26) in phar:///home/pi/pocketmine/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 143
[16:25:34] [Server thread/INFO]: Enabling Lightning_Strike v2
[16:25:34] [Server thread/INFO]: [Lightning_Strike] Lightning Strike RUNNING Made By MichaelM04
[16:25:34] [Server thread/INFO]: Enabling PurePerms v1.3.6
[16:25:34] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1.
[16:25:34] [Server thread/INFO]: Enabling PureChat v1.4.0
[16:25:34] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[16:25:34] [Server thread/INFO]: Starting GS4 status listener
[16:25:34] [Server thread/INFO]: Setting query port to 19132
[16:25:34] [Server thread/INFO]: Query running on 0.0.0.0:19132
[16:25:35] [Server thread/INFO]: Default game type: Survival Mode
[16:25:35] [Server thread/INFO]: Done (2.568s)! For help, type "help" or "?"
[16:25:35] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed
`

**Comment by TheDeibo** [comment]
I am aware of a problem with this. I am fixing it now

**Comment by jingz2007** [comment]
Actually, I think it was my fault because I accidentally didnt close the one ran when my raspi starts up so it crashed. Now that I restarted it works fine and I can join it from 0.14.1 MCPE.

**Comment by TheDeibo** [comment]
This pull has been fixed and moved to
 https://github.com/PocketMine/PocketMine-MP/pull/4115
Or to download it quickly, use 
http://pmt.mcpe.me/pmb/dl/pr:4115.phar

**Pull request closed without merging**
