### PR TITLE
Update start.sh

### PR DESCRIPTION
**Pull request by adrianwebster**
Add wait for 10 seconds

### CODE REVIEW

**Comment by 64FF00** [comment]
O_o?

**Comment by adrianwebster** [comment]
It adds wait for ten seconds (sleep) before it exits for user to be able to read error without instantly closing

**Comment by adrianwebster** [comment]
I just realized i forgot to do both...

**Comment by ns827** [comment]
Linux terminal emulator does not close the window automatically when the program exits. I don't know why this patch is useful.

**Comment by Falkirks** [comment]
@ns827 Doesn't the windows shell close out?

**Comment by ns827** [comment]
@Falkirks I don't know because I use only Ubuntu, but I remember mintty prints segmentation fault message on 'normal' server stop.

\+ This pull request is about bash shell scripts, not windows batch.

**Comment by adrianwebster** [comment]
Ok nvm just dont merge it I understand now lol i never had the error but i just assumed it closed but it doesnt xD

**Comment by 64FF00** [comment]
@ns827 :+1:

**Pull request closed without merging**
