### PR TITLE
changed weird ban kick message

### PR DESCRIPTION
**Pull request by PocketKiller**
https://github.com/ImagicalCorp/ImagicalMine/commit/23f20d99f93ac97f60fe4ef93f7bd419c7be4432
and kick() function on Player.php $isAdmin.

### CODE REVIEW

**Comment by Intyre** [comment]
Can you explain why you added ``false``? Only admins can use the ``/ban`` command.

**Comment by PocketKiller** [comment]
look at `Player.php` on the kick function : 
```php
<?php
public function kick($reason = "", $isAdmin = true){
		$this->server->getPluginManager()->callEvent($ev = new PlayerKickEvent($this, $reason, $this->getLeaveMessage()));
		if(!$ev->isCancelled()){
			if($isAdmin){
				$message = "Kicked by admin." . ($reason !== "" ? " Reason: " . $reason : "");
			}else{
				if($reason === ""){
					$message = "disconnectionScreen.noReason";
				}else{
					$message = $reason;
				}
			}
			$this->close($ev->getQuitMessage(), $message);
			return true;
		}
		return false;
	}
?>
```
as your code in the ban command, if the player is banned without reason he'll be kicked with the message "Kicked by admin. reason: banned by admin.
and if there is a reason.. "Kicked by admin. reason: banned by admin. reason: test
because as default in kick() function isAdmin is true, and if it's true, it adds that "Kicked by admin. reason.." but with false and there is a reason, he'll be kicked as the reason without any additions.

**Comment by iksaku** [comment]
Well, the current code changed doesn't makes sense, instead I would suggest to change the "Reason parsing" inside the `kick()` function, so it is more dynamic and can be adapted to the `/ban` command

**Comment by Intyre** [comment]
Something like 78525e1f74e01d8c0cc?

**Comment by iksaku** [comment]
@Intyre That's it ;) Thanks :3

**Pull request closed without merging**
