### PR TITLE
Update PigZombie.php

### PR DESCRIPTION
**Pull request by FatalDeath**

### CODE REVIEW

**Comment by PEMapModder** [comment]
Why are there so many empty lines before the EOF? To get contribution lines?

And right now this is useless unless you use it somewhere.

**Comment by sekjun9878** [comment]
Please remove the extra newlines before this can be considered for merge to master.

**Comment by Falkirks** [comment]
@FatalDeath also when you remove the new lines it would be optimal if you squash the commits, that way there isn't a commit on master that is just removing line breaks :smile:

**Comment by shoghicp** [comment]
Mobs won't be partially implemented. This was done for Zombies and Villagers, and it was a bad idea.

**Pull request closed without merging**
