### PR TITLE
Cacti + Sugarcane

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Fixing crashes when the plants are too high and broken (without xdebug
no crash but server freeze) and some logic fixes. Cacti + Sugarcane do
grow naturally onTick, but using Bonemeal on sugarcane will not be sendt
by the client (MCPE).
https://bugs.mojang.com/browse/MCPE-15102

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
#3752 #3806

**Comment by jasonwynn10** [comment]
Does this apply to pmmp's PocketMine?

**Comment by thebigsmileXD** [comment]
Closed because of ban + outdated unformatted code.

**Comment by thebigsmileXD** [comment]
@jasonwynn10 in theory the problems were "reduced", these loops still appear in pmmp. Ask dktapps about it. The growth script worked though, but things will change to allow different tick times for ticking blocks.

**Pull request closed without merging**
