### PR TITLE
Implemented hardcore banning

### PR DESCRIPTION
**Pull request by LDX-MCPE**
I'm not sure if I should kick the player or not.

### CODE REVIEW

**Comment by sekjun9878** [comment]
Hmm.. interesting. If the player is dead then you should kick the player otherwise he could just respawn? Or is the respawn blocked somewhere

**Comment by PEMapModder** [comment]
No, you should kick the player.

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/Player.php#L2024-2027

From the above link, we can see that PocketMine does not seem to detect if a player is banned when he dies.

**Comment by PEMapModder** [comment]
https://github.com/LDX-MCPE/PocketMine-MP/pull/1

**Comment by LDX-MCPE** [comment]
I wondered about that. That's why I said:
> I'm not sure if I should kick the player or not.

**Pull request closed without merging**
