### PR TITLE
Promotes the use of reactions

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by robske110** [comment]
Do you want them?
I thought here everything should be clean ...

**Comment by Falkirks** [comment]
Reactions are much preferred to users creating comments, with things like `:+1:` or other emojis.

**Comment by thebigsmileXD** [comment]
To say it with PocketMine words:

This issue is not related to PocketMine.

**Comment by thebigsmileXD** [comment]
Hahaha, removed my comment because you didn't like it?

**Comment by PEMapModder** [comment]
@thebigsmileXD I don't know who did or what happened, but please, if you want to talk about things that are not related to the issue itself, please use our forums or the IRC channel. The issue tracker is **not** a forum.

**Pull request merged**
