### PR TITLE
Cleaner (and maybe faster) INI parsing at BaseLang.php

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by SkygridRex** [comment]
have you tested that?

**Comment by PEMapModder** [comment]
@SkygridRex from the look of the code, I don't think anything could probably go wrong with that. But for your information, yes.

**Comment by willowmaster66** [comment]
There is a possibility that $t[1] will fail. In the old code it wouldn't. I think you have to check if index 1 exists.

**Comment by PEMapModder** [comment]
@willowmaster66 what is [this](https://github.com/PocketMine/PocketMine-MP/pull/3663/files#diff-027ad9b90052a706797368dcecb525e2R65)?

```php
 				if(count($t) < 2){
 					continue;
 				}

**Comment by willowmaster66** [comment]
@PEMapModder I have overlooked that. It can not go wrong then. :)

**Comment by SkygridRex** [comment]
You've heard the saying "if something works well do not touch"?

**Comment by willowmaster66** [comment]
@SkygridRex If everyone would think like that nothing would improve. Saving some cpu cycles doesn't seem like a lot, but it does in the big picture I think.

**Comment by PEMapModder** [comment]
It doesn't actually affect a lot in terms of performance since it is only used in startup code (for core). But still, cleaner code is always better.

**Pull request merged**
