### PR TITLE
Revert 2 herofied1180 patch 1

### PR DESCRIPTION
**Pull request by Herofied1180**
Adds support for 0.14.1 and 0.14.0.

### CODE REVIEW

**Comment by Herofied1180** [comment]
How do I get my phar download for my pull request?

**Comment by extremeheat** [comment]
... _test out PRs locally before you submit them publicly to a repo_. You don't need 3 PRs for the **same exact thing** -- if you were rejected once, why would you abruptly make another PR? Have you implemented the 0.14.1 protocol changes? I don't see that (and if you don't know what changed, you should not be making updating the protocol version).

Squash your commits (I've said this twice), implement the protocol changes and stop getting ahead of yourself. It's not just a matter of changing some files, and saying "I'm done."

**Comment by Herofied1180** [comment]
Well how do I just access my phar file here to my pull request (I'm a newbie btw to the pocketmine dev world and I think that what your saying is offensive)? I am deleting your post.

**Comment by Herofied1180** [comment]
Oh wait I can't! [DARN IT YOU SUCKER]

**Comment by Intyre** [comment]
Protocol changes are there for a reason. Don't accept multiple protocol version!
12 Commits for a small change? Squash it!
Need more help? Use the [forums](https://forums.pocketmine.net)!

**Pull request closed without merging**
