### PR TITLE
Fix Crashes on Level.php

### PR DESCRIPTION
**Pull request by Samueljh1**
Fixes the Infamous getChunk() on null error!

### CODE REVIEW

**Comment by shoghicp** [comment]
Ehh...
No. This does not fix the issue and is a really bad hack.

**Comment by Samueljh1** [comment]
Hack? And it does. On my SkyWars server, if I tried to unload and load a level, it can sometimes crash. I modified Level.php to check all usages of $this->provider is an instanceof err.. What was it? LevelBaseProvider? Anyway the server hasn't crashed since! (You should because the server will crashes when trying to load/unload some levels.) They are PC levels. It has happened a lot on my other server too!

**Comment by shoghicp** [comment]
You might not be unloading worlds properly. Don't use Level->unload();

**Comment by Samueljh1** [comment]
I used Server::getInstance->unloadLevel() should there be a different method?

**Comment by shoghicp** [comment]
Also, if you are still getting chunks there are other issues with that level.

**Pull request closed without merging**
