### PR TITLE
Corrected attribute constants

### PR DESCRIPTION
**Pull request by PEMapModder**
With reference to Hydreon/Katana AttributeManager constants

### CODE REVIEW

**Comment by GODLIKE5** [comment]
Bro i can try to help the hunger in pocketmine for regeneration... i just need to know how to make the Pocketmine-MP.zip into a phar.. @PEMapModder

**Comment by PEMapModder** [comment]
@GODLIKE5 does making PocketMine into a phar affect developing hunger at all?

**Comment by GODLIKE5** [comment]
No.. but i have made a plugin that makes hunger work... so i need to know how to make the zip from pocketmine a phar.. i already tried pmt.mcpe.me but thats just for plugins..

**Comment by GODLIKE5** [comment]
( so i can add hunger )

**Comment by PEMapModder** [comment]
@GODLIKE5 

1. This is not a forum.
2. Implementing hunger from a plugin is different from that in PocketMine itself.
3. Actually, I'm implementing it now.

**Comment by GODLIKE5** [comment]
ok :( but can you at least tell how so i can do other testing things like different item names?
or freecraft?

**Comment by PEMapModder** [comment]
@GODLIKE5 this is **not** a forum.

**Comment by PEMapModder** [comment]
Closed by #3758

**Pull request closed without merging**
