### PR TITLE
Added getter for speed

### PR DESCRIPTION
**Pull request by luca28pet**

### CODE REVIEW

**Comment by Intyre** [comment]
What is the reason behind this?
```php
$speed = $player->speed;      // works fine
$speed = $player->getSpeed(); // works too but why?
```

**Comment by robske110** [comment]
Because we then can actually. Erm. Er. Hmm. 
Ah! Make the speed variable private

**Comment by luca28pet** [comment]
Didn't see $player->speed was public

**Comment by luca28pet** [comment]
Holy crap you're so funny rob

**Comment by robske110** [comment]
That ironic smell
And now @Intyre will lock it and edit this comment, because i wrote this

**Pull request closed without merging**
