### PR TITLE
Update PocketMine.php

### PR DESCRIPTION
**Pull request by ZenaGamingsky**

### CODE REVIEW

**Comment by matcracker** [comment]
What are doing? :/

**Comment by Pub4Game** [comment]
omg. Please stop create invalid pull request

**Comment by DRedDogPE** [comment]
sorry to burst your bubble but i already did all this and made it work.

**Comment by PEMapModder** [comment]
Please stop...
zena

**Comment by DRedDogPE** [comment]
STOP!!!

**Comment by tiNsLeY799** [comment]
Stop sending the PRs. They don't work and someone already did it.

**Comment by SkygridRex** [comment]
@RedDogPE Nope didnt work like fishing rod

**Comment by Intyre** [comment]
## Contributing Code

- Use the Pull Request system, your request will be checked and discussed.
- Create a single branch for that pull request
- Code using the syntax as in PocketMine-MP. See below for an example.
- The code must be clear and written in English, comments included.
- Use descriptive commit titles
- **No merge commits are allowed, or multiple features per pull request**

**Pull request closed without merging**
