### PR TITLE
Clean update to 0.14.2(.0)

### PR DESCRIPTION
**Pull request by robske110**
TODO: Implement the 2 new packets

### CODE REVIEW

**Comment by Intyre** [comment]
MCPE version looks like `major.minor.patch.beta`

**Comment by jojoe77777** [comment]
@Intyre yes, but personally I don't think it's necessary to include it when it's 0; just like how you don't type numbers like this: 5.0 or 5.20; the 0s at the end are redundant imo.

**Comment by extremeheat** [comment]
Client built-in server also seems to use "0.14.1" when broadcasting but we may want to stick to "0.14.1.0" for consistency's sake.

**Comment by robske110** [comment]
>> Client built-in server also seems to use "0.14.1" when broadcasting but we may want to stick to "0.14.1.0" for consistency's sake. Either way I don't think this matters really.
But I think they internally use 0.14.1.0 ?!

**Comment by TheDeibo** [comment]
The "0" is needed.
Please take notice of this.

https://github.com/PocketMine/PocketMine-MP/commit/9acbd85b256bcc18258ef8b8c0913d6d3b7becc7

**Comment by TheDeibo** [comment]
004a8264 <SharedConstants::getVersionCode()>:
  4a8264:   2000        movs       r0, #0   // MajorVersion
  4a8266:   210e        movs       r1, #14  // MinorVersion
  4a8268:   4602        mov        r2, r0   // PatchVersion
  4a826a:   4603        mov        r3, r0   // BetaVersion
  4a826c:   f7ff bfe6   b.w 4a823c <SharedConstants::getVersionCode(int, int, int, int)>

**Comment by TheDeibo** [comment]
004a8264 <SharedConstants::getVersionCode()>:
    4a8264:   2000        movs       r0, #0   // MajorVersion
    4a8266:   210e        movs       r1, #14  // MinorVersion
    4a8268:   4602        mov        r2, r0   // PatchVersion
    4a826a:   4603        mov        r3, r0   // BetaVersion
    4a826c:   f7ff bfe6   b.w 4a823c <SharedConstants::getVersionCode(int, int, int, int)>

**Comment by Muqsit** [comment]
*MCPE 0.14.2*

**Comment by TheDeibo** [comment]
Yes. I know.

**Comment by Driesboy** [comment]
dont work!!!

**Comment by robske110** [comment]
What doesn't work

**Comment by Driesboy** [comment]
you cannot break blocks!!!

**Comment by Muqsit** [comment]
0.14.2 protocol is 60, not 47 and there are some block packets that have changed

**Comment by extremeheat** [comment]
This is nice, maybe people will start implementing protocol changes instead of just changing versions ;)

A bit of UI changes in the client too, from my first looks.

**Comment by robske110** [comment]
Yes, i did notice it too, already working on it

**Comment by TheDeibo** [comment]
```
     +	const MINECRAFT_VERSION = "v0.14.2 beta";
     +	const MINECRAFT_VERSION_NETWORK = "0.14.2.0";
```
Im pretty sure its supposed to follow this. 


    004a8264 <SharedConstants::getVersionCode()>:
    4a8264:   2000        movs       r0, #0   // MajorVersion
    4a8266:   210e        movs       r1, #14  // MinorVersion
    4a8268:   4602        mov        r2, r0   // PatchVersion
    4a826a:   4603        mov        r3, r0   // BetaVersion
    4a826c:   f7ff bfe6   b.w 4a823c <SharedConstants::getVersionCode(int, int, int, int)>

Yet again, it comes from https://github.com/PocketMine/PocketMine-MP/commit/9acbd85b256bcc18258ef8b8c0913d6d3b7becc7

Wow, am I repeating myself?

**Comment by robske110** [comment]
It is following it

**Comment by TheDeibo** [comment]
Not quite. 

As I see it, your version resembles this


    004a8264 <SharedConstants::getVersionCode()>:
    4a8264:   2000        movs       r0, #0   // MajorVersion
    4a8266:   210e        movs       r1, #14  // MinorVersion
    4a8268:   4602        mov        r2, rMESSED-UP-Junk   // PatchVersion
    4a826a:   4603        mov        r3, r0   // BetaVersion
    4a826c:   f7ff bfe6   b.w 4a823c <SharedConstants::getVersionCode(int, int, int, int)>

whereas its supposed to be


    004a8264 <SharedConstants::getVersionCode()>:
    4a8264:   2000        movs       r0, #0   // MajorVersion
    4a8266:   210e        movs       r1, #14  // MinorVersion
    4a8268:   4602        mov        r2, r2   // PatchVersion
    4a826a:   4603        mov        r3, r0   // BetaVersion
    4a826c:   f7ff bfe6   b.w 4a823c <SharedConstants::getVersionCode(int, int, int, int)>

**Pull request closed without merging**
