### PR TITLE
Added and rearranged all the creative tools.

### PR DESCRIPTION
**Pull request by mightysun99**
Added Diamond,Gold,Stone and Wood tools to the creative inventory.

### CODE REVIEW

**Comment by shoghicp** [comment]
I still don't understand why you want all the tools in creative, even when they don't give extra benefit (except swords). This was a debug thing on MCPE that got by error into a build then it was left there

**Comment by PEMapModder** [comment]
@shoghicp since most of the community doesn't seem to hate it, I think you'd better keep it.

**Comment by mightysun99** [comment]
@shoghicp I wasn't aware this was a debug feature i don't really care what you do with it keep or remove it. Had some spare time and thought id do it.

**Comment by matcracker** [comment]
#3057 Duplicate

**Comment by mightysun99** [comment]
@matcracker didn't even realise this existed probably due to the fact it was closed.

**Comment by iksaku** [comment]
@matcracker But what if @mightysun99  properly arranged all the items? This isn't duplicated at all :P

**Comment by mightysun99** [comment]
@iksaku These have been arranged to match the single player creative inventory i believe @matcracker didn't do this.

**Comment by matcracker** [comment]
In my request I placed all the tools as in singleplayer, had done well as a screen

**Comment by mightysun99** [comment]
Not for the stone tools you didn't replicate the creative inventory. @matcracker

**Comment by thebigsmileXD** [comment]
I think all items and blocks that are already working should be available in the creative inventory.

**Comment by PEMapModder** [comment]
Obsolete pull request, code is now already present.

**Pull request closed without merging**
