### PR TITLE
0.14.1 Update For client and server

### PR DESCRIPTION
**Pull request by Herofied1180**
In this pull request I will be updating the PocketMine Server **MINECRAFT_VERSION** (Which will be the MC version the server accepts) & **MINECRAFT_VERSION_NETWORK** (Which will be the MC version the server runs on). It will make MC version 0.14.1 compatible with this server and, MC 0.14.1.
It will also solve the problem in the issue forum thread #4127. That is about all I can think of that I can say, so have a great day enjoying PocketMine in MC 0.14.1! ;)

### CODE REVIEW

**Comment by extremeheat** [comment]
You can't simply just change some strings and expect for things to work. This PR will not allow 0.14.1 clients to join -- you need to change the protocol version for that.

Furthermore, before you commit a PR you aught to have a bit of familiarity with the project that you're contributing to... let alone follow the contributing guidelines.

There is no good reason to add messages like "join with x client version" to the server log, it is unnecessary information.

**Comment by Herofied1180** [comment]
I am sorry, I will get right to it later but right now I have other things to worry about so I will lock this until tommorrow. Good Night everyone!

**Comment by Herofied1180** [comment]
Good Morning peeps! It's very early for me but i might be able to code a little.

**Comment by Herofied1180** [comment]
I am editing the Network Protocol immidently

**Comment by Herofied1180** [comment]
Ok does anyone know what the network protocol (e.g. MC protocol version) should be?

**Comment by Herofied1180** [comment]
Ok doing Major string bug fix

**Comment by Herofied1180** [comment]
Finally success! I can't wait to try this out! ;) Enjoy the PocketMine update to 0.14.1!

**Comment by extremeheat** [comment]
This still does not resolve any of the issues I stated...

You still have the unneeded console messages, changes to irrelevant things, and a whole bunch of poorly named commits which should be squashed.

Have you looked into the protocol changes either before you updated the protocol version? Your PR looks just like #4115 which was closed for not accounting for protocol changes.

**Pull request closed without merging**
