### PR TITLE
Added base translation ko_KR.ini

### PR DESCRIPTION
**Pull request by HmHmmHm**
PM Korean translation work completed

### CODE REVIEW

**Comment by shoghicp** [comment]
Nice!
It's not ready for Crowdin yet, but I'll upload it there soon :)

**Comment by shoghicp** [comment]
You can now translate it on http://translate.pocketmine.net/translate/pocketmine/21/en-ko

I've uploaded the already existing translations.

**Comment by 64FF00** [comment]
:+1: Keep up the great work @HmHmmHm! Really love it <3

**Comment by shoghicp** [comment]
@64FF00 You can also help everyone at http://translate.pocketmine.net/translate/pocketmine/21/en-ko and vote the best ones (there are already a few ones!)

**Comment by 64FF00** [comment]
@shoghicp I wish I could, but I have midterms in a few weeks :'(

**Pull request closed without merging**
