### PR TITLE
Update Utils.php

### PR DESCRIPTION
**Pull request by SopaXorzTaker**
Correct a typo

### CODE REVIEW

**Comment by SopaXorzTaker** [comment]
No need to push in master.

**Comment by PEMapModder** [comment]
Where should it be if it isn't master?

**Comment by SopaXorzTaker** [comment]
Oops, I have managed to mess it up. There is only master no develop.
Releases aren't made by branches.

**Comment by SopaXorzTaker** [comment]
@PEMapModder I think it needs to be reopened.

**Pull request closed without merging**
