### PR TITLE
Fixed the error "BlockHash must type of Interger"

### PR DESCRIPTION
**Pull request by DELOS-phardev**
###Must Type Of Interger !
(int)
(int)
(int)
(int)
(int)(int)(int)(int)

### CODE REVIEW

**Comment by DELOS-phardev** [comment]
It is an Fatal Error !

**Comment by PEMapModder** [comment]
First we have to find out why $pos->x would be a non-integer. The problem should be fixed from the source.

**Comment by DELOS-phardev** [comment]
@PEMapModder Plugin Developers cannot use "getLevel()->getBlock()" method now , because of this Error

**Comment by PEMapModder** [comment]
@DELOS-phardev plugin developers should not have passed a floating point vector to getBlock() in the first place, right?

**Comment by robske110** [comment]
Hey! Wait this should be float

**Comment by robske110** [comment]
@PEMapModder They should do that and do that!
As example if you want to get an block below the player you subtract -1 from y and then pass the FLOAT values to the getBlock

**Comment by PEMapModder** [comment]
Now? This is not a real issue, but adds convenience to developers.

**Comment by robske110** [comment]
Hey $pos->floor will not work with negative numbers

**Comment by PEMapModder** [comment]
@robske110 negative numbers have nothing to do with int/float.

**Comment by robske110** [comment]
But floor() won't work on negative values

**Comment by PEMapModder** [comment]
@robske110 it does. `(int) floor(-0.5)` results in -1, which is correct.

**Comment by robske110** [comment]
It's not
when you are on pos -0.5 you are on block 0 not -1!!!!!!

**Comment by robske110** [comment]
```php
        function truncate_float($number, $behindNumber) {
            $amp = pow(10, $behindNumber);
            if($number > 0){
                return floor($number * $amp) / $amp;
            }else{
                return ceil($number * $amp) / $amp;
            }
        }
```

**Comment by PEMapModder** [comment]
From PHP.net:

> Returns the next lowest integer value (as float) by rounding down value if necessary.

We want to round down -1.5 to -2, not -1. And that's what `floor()` does.

```shell
$ php -r 'var_dump(floor(-1.5), (int) floor(-1.5));'
float(-2)
int(-2)
```

and this is the correct behaviour. We want to round down, not to round to the integer closer to 0.

**Comment by DELOS-phardev** [comment]
Hmm.. Then .. Let's Blame ShoghiCP !
@PEMapModder

**Comment by ZINGDING** [comment]
@DELOS-phardev 
That's Good!

**Comment by robske110** [comment]
Blame me

**Pull request closed without merging**
