### PR TITLE
Redstone has to break 5 times to be finally mined.Attempt 2

### PR DESCRIPTION
**Pull request by willowmaster66**
I have changed two values to match the values in RedstoneOre.php and removed the extend to RedstoneOre and other deletes. Just the two values. :)

### CODE REVIEW

**Comment by SkygridRex** [comment]
Are you using the same values of RedstoneOre.php?

**Comment by willowmaster66** [comment]
I thought I did. Now you make me doubt. Do you think not?

**Comment by willowmaster66** [comment]
I checked it again. These are the same values as RedstoneOre.php

**Comment by willowmaster66** [comment]
I also fixed the fact that the RedstoneOre starts out as GlowingRedstoneOre. It will now become GlowingRedstoneOre after hitting it for the first time.

**Pull request closed without merging**
