### PR TITLE
Delete NetherReactor.php

### PR DESCRIPTION
**Pull request by ZenaGamingsky**

### CODE REVIEW

**Comment by Pub4Game** [comment]
@ZenaGamingsky Stop doing it!

**Comment by TahaTheHacker** [comment]
All checks have failed
1 errored check
YOU need to do more to remove this, but Stop!

**Comment by SkygridRex** [comment]
@shoghicp Can you ban him?

**Comment by iVertx** [comment]
@intyre, @sekjun9878...

200 watcher's mail boxes will be really happy with that...

**Comment by sekjun9878** [comment]
fsck. Sorry about the mailbox spam.

@ZenaGamingsky While I'm sure you're genuinly eager to contribute to the PocketMine project, the patches you've provided us are unusuable. I've marked all of your PR requests invalid and closed. Please refrain from making PR requests in the future. Thanks for your consideration!

**Pull request closed without merging**
