### PR TITLE
Implemented proportional armor damage, armor consumption on damage and added armor protection for more damage types (Take 2)

### PR DESCRIPTION
**Pull request by PEMapModder**
I used copy and paste and then manually put recent changes into the code, so there are some accidental OCD fixes in the code, which would not cause a problem.

(Cont #2776)

### CODE REVIEW

**Comment by iJoshuaHD** [comment]
woot woot! \o/

**Comment by sekjun9878** [comment]
@PEMapModder can you rebase your commits so that you are not editing the PocketMine-MP header snippet? The current diff is adding and removing spaces on the header.

**Comment by shoghicp** [comment]
Can you finish this for 1.5 integration?

**Comment by PEMapModder** [comment]
Is it simply conflict resolving, or more?

**Comment by shoghicp** [comment]
@PEMapModder there were some changes, including potions (they don't do damage as well)

**Comment by PEMapModder** [comment]
Closed #3285

**Pull request closed without merging**
