### PR TITLE
Fixed hotbar has too many slots

### PR DESCRIPTION
**Pull request by thebigsmileXD**
The hotbar is only 6, not 9 big..

### CODE REVIEW

**Comment by PEMapModder** [comment]
The hotbar size depends on the GUI size. 9 is the maximum size possible (you can see taht in win10)

**Comment by thebigsmileXD** [comment]
@PEMapModder but this is the branch for 0.11. The Win10 Version is only made for 0.12 or higher

**Comment by PEMapModder** [comment]
Also, the NBT structure follows the MCPC format, which is obviously 9 slots.

**Comment by thebigsmileXD** [comment]
Slots that are offset are selected or can be selected. And the inventory size

**Comment by thebigsmileXD** [comment]
Also, in my oppinion it should be saved into a variable. public $hotbarSize = 9||6;

**Comment by iksaku** [comment]
Why should you need to `limit` players' hotbar? They're free to use whichever UI style they want! (Depending on their client screen size...)

**Comment by thebigsmileXD** [comment]
hmm.. But still. Maybe thats the problems that slots that DONT EVEN EXIST in the GUI are selected. Cant find a picture right now..

**Comment by PEMapModder** [comment]
@thebigsmileXD what's wrong with having an item in your hotbar but you can't see it? As long as you aren't holding it is not a problem. You are always able to move items from other hotbar slots or not in hotbar slots into your current hotbar slot using MCPE GUI.

BTW, if you adjust your D-Pad size you will have more or less slots.

**Comment by thebigsmileXD** [comment]
That is now what i mean. You know the selection box around the item you currently use? Somethimes this box gliched out and selects a slot that doesn't exist right to the the three dots where you open the inventory.
https://forums.pocketmine.net/attachments/image-jpg.9255/

**Comment by PEMapModder** [comment]
This is a client issue. It is impossible for PocketMine to know what the client hotbar size is, so of course we would take the maximum possible value.

**Comment by thebigsmileXD** [comment]
In 0.11 its 6.

**Comment by PEMapModder** [comment]
I had 7 slots since the update that let you adjust D-Pad size...

**Comment by thebigsmileXD** [comment]
I think it always happens if you change gamemode and then select any block that was in your survival inventory before.

**Pull request closed without merging**
