### PR TITLE
Create PlayerHungerEvent.php

### PR DESCRIPTION
**Pull request by sero583**
I'm not sure, but isn't this missing anyways?

### CODE REVIEW

**Comment by extremeheat** [comment]
What's the point of creating this useless event?

**Comment by sero583** [comment]
@extremeheat That event is called, if the hunger from the player changes, i don't think, it's useless at all.

**Comment by extremeheat** [comment]
Where is it called?

**Comment by sero583** [comment]
@extremeheat I don't know what you trying to tell me, how do you mean 'Where is it called'?

**Comment by extremeheat** [comment]
You said that the **event is called when the hunger from the player changes**. I'm asking where in the code this event is called.

**Comment by sero583** [comment]
@extremeheat I don't know, anyways someone should correct this event a bit xD

**Pull request closed without merging**
