### PR TITLE
0.12.3 New Blocks, Items, Enchantments, Effects

### PR DESCRIPTION
**Pull request by DRedDogPE**
The thing the players on my server loved most was... working double flowers... 

## ToDo:
- Make brewing stand brew potions
- Make flowers drop from bonemealing two block flowers
- Add crafting recipes for updated stuff
- Figure out why it some times says the version is v0.13.0 when it is v0.12.3
- Fix any crashes that get reported
- Make rails connect to nearby rails and allow curves and slopes
- Allow enchanting using NAME or ID of enchantment
- Fix Brewing Stands not being able to be broke in survival
- Enable flowers to be put in Flower Pot

### CODE REVIEW

**Comment by TahaTheHacker** [comment]
:+1:

**Comment by DRedDogPE** [comment]
:+1:  yay

**Comment by SavionLegendZzz** [comment]
goog job :+1: :D

**Comment by DRedDogPE** [comment]
@SavionLegendZzz Thanks. Took a couple of days and plenty of crashes!

**Comment by SavionLegendZzz** [comment]
question. does enchantment work? like does it apply the enchant and the enchant works?

**Comment by DRedDogPE** [comment]
It will apply the enchantment but i have not yet implimented the effects for them. so im not sure if they work

**Comment by D3thw0lf** [comment]
:+1: <3

**Comment by DRedDogPE** [comment]
Im working on the current crashes. I should be able to push in a couple of mins.

**Comment by D3thw0lf** [comment]
pawsome :)

**Comment by DRedDogPE** [comment]
@TahaTheHacker  @SavionLegendZzz  @D3thw0lf  @wallace  @greyson  If you have any problems whilst using this please could you let me know so that i can fix it asap. also the crashes i have found so far should be fixed (Brewing Stand GUI used to crash)

**Comment by SkygridRex** [comment]
I have a doubt. To enchant need to know the ID's of incantations or put the name of the spell or I can use both?

**Comment by DRedDogPE** [comment]
You have to use the id but i might impliment a way to search using names or make a list of the enchantment id's with a command so that you can view it ingame

**Comment by SkygridRex** [comment]
@DRedDogPE this like me! but i gess PocketMine Team don't Merge this change curiously does not like extreme changes

**Comment by DRedDogPE** [comment]
I take it my shameless self promotion got removed or I never put it and I'm just crazy?

**Comment by D3thw0lf** [comment]
I'm glad you're crazy and tryin' to change things... :3

**Comment by cokll** [comment]
:+1:

**Comment by translateRussian** [comment]
:+1:

**Comment by DRedDogPE** [comment]
I'm starting to work on adding flower pot flower support and brewing recipes. Then I will do Skull Support.

**Comment by Intyre** [comment]
Nice work! But group related changes.
If we merge this we also get the changes made to CrashDump.php, Player.php and PocketMine.php.

Some of those are not needed.
CrashDump.php: Is it really needed to put crash dumps in a new directory?
Player.php: The changes to hasPermission are bad, all crash i've seen are caused by plugins and should be fixed in the plugins.
PocketMine.php: Versions should only be bumped by shoghi

**Comment by DRedDogPE** [comment]
@Intyre I removed the commits i made to work with my server. The rest of the edits are for the new blocks and items.

**Comment by SkygridRex** [comment]
@DRedDogPE You can make your own distribution of PocketMine following your own rules

**Comment by DRedDogPE** [comment]
@SkygridRex What do you mean exactly?

**Comment by SkygridRex** [comment]
@DRedDogPE PocketMine say's in your license you can modify it

**Comment by DRedDogPE** [comment]
@SkygridRex Yeah i know thats why i have my own version in my server's repo.

**Comment by DRedDogPE** [comment]
I would be able to test all of the edit i make alot easier if hosting services allowed you to run from source code. (HostingItAll, MultiCraft)

**Comment by SkygridRex** [comment]
@DRedDogPE Replace PocketMine-MP.phar?

**Comment by DRedDogPE** [comment]
@SkygridRex It takes time to create the .phar file.

**Comment by SkygridRex** [comment]
@DRedDogPE I use an strange and functional form to create a .phar file fast

**Comment by DRedDogPE** [comment]
@SkygridRex How?

**Comment by SkygridRex** [comment]
@DRedDogPE Can you Create a gitter chat i don't wanna say this here

**Comment by DRedDogPE** [comment]
@SkygridRex I added you to a chat.

**Comment by PEMapModder** [comment]
@SkygridRex @DRedDogPE this is not a forum.

**Comment by willowmaster66** [comment]
I think you can make phar files with the dev tools I think.

**Comment by PEMapModder** [comment]
Blocks like rails are not added because they are not supported yet.
Also, please, rebase your commits into one.

**Comment by SkygridRex** [comment]
@PEMapModder let me in peace

**Comment by Intyre** [comment]
## Contributing Code

- Use the Pull Request system, your request will be checked and discussed.
- Create a single branch for that pull request
- Code using the syntax as in PocketMine-MP. See below for an example.
- The code must be clear and written in English, comments included.
- Use descriptive commit titles
- **No merge commits are allowed, or multiple features per pull request**

**Pull request closed without merging**
