### PR TITLE
Bump to 0.14.2.0

### PR DESCRIPTION
**Pull request by TheDeibo**
Bump to 0.14.2.0

Like I've done for 0.14.1.0, I have simply updated 2 files to allow players to join the server. 
They will be some missing protocols, but I just simply provided a little bridge-way to success

### CODE REVIEW

**Comment by Driesboy** [comment]
i cannot break blocks

**Comment by TheDeibo** [comment]
Have you tried this one?

**Comment by Driesboy** [comment]
yes

**Comment by TheDeibo** [comment]
What device have you got?

**Comment by Driesboy** [comment]
iOS

**Comment by PrimusLV** [comment]
Protocol bump means something were changed in packets and is no longer compatible with older versions. You can't just change few numbers and call it bump.

**Comment by TheDeibo** [comment]
Wrong term of phrase. Dont shoot me down for it.

Just incase, here is a phar format of this pull
http://notpocketmine.tk/pmb/dl/pr-4153.phar

**Comment by TheDeibo** [comment]
My Bad. it wont towk on win10, but will on my ipad. :/ ill recheck.

**Pull request closed without merging**
