### PR TITLE
added double tall grass

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by TahaTheHacker** [comment]
:+1:

**Comment by thebigsmileXD** [comment]
:+1: Nice fix ^^ waited for it too long ;)

**Comment by DRedDogPE** [comment]
Hm, ill add this into my server :) I will also try to add the second half of all the double plants.

**Comment by dktapps** [comment]
This is obsoleted by changes in the PMMP repository.

**Pull request closed without merging**
