### PR TITLE
A tombstone

### PR DESCRIPTION
**Pull request by Tee7even**

### CODE REVIEW

**Comment by Charelene** [comment]
image

**Comment by Pub4Game** [comment]
LEL

**Comment by translateRussian** [comment]
goodbye, PM, hello, MiNET

**Comment by Pub4Game** [comment]
@translateRussian or Nukkit :)

**Comment by translateRussian** [comment]
@Pub4Game PM++ and PM1.7 by ImagicalCorp :D

**Comment by Tee7even** [comment]
@translateRussian MiNET made for minigames, Nukkit will be great as software for more general purpose

**Pull request closed without merging**
