### PR TITLE
Fixes a bug with the slots

### PR DESCRIPTION
**Pull request by Pub4Game**
image

### CODE REVIEW

**Comment by PEMapModder** [comment]
Does your image explain anything at all?

**Comment by Pub4Game** [comment]
What's wrong?

**Comment by Pub4Game** [comment]
I don't understand what you mean... I have everything working perfectly

**Comment by PEMapModder** [comment]
@Pub4Game why did you use `close()` rather than `kick()`?

**Comment by PEMapModder** [comment]
I'm unable to reproduce the issue you reported.

It works with 0/0

**Comment by Pub4Game** [comment]
Okay, I will fix it

**Comment by PEMapModder** [comment]
@Pub4Game fix what? Did you not see my image? This issue cannot be reproduced using the latest master build.

I have also tested with one player:



This shows that the server full mechanism is working correctly.

**Comment by Pub4Game** [comment]
@PEMapModder 

I used 'close()' because if you use the 'kick()', then the following happens
image

**Comment by PEMapModder** [comment]
@Pub4Game without plugins? And are you using official PocketMine?

**Comment by Pub4Game** [comment]
Yes..

**Comment by PEMapModder** [comment]
@Pub4Game I am unable to reproduce that issue using the latest development build.

**Pull request closed without merging**
