### PR TITLE
Finally signs drop..

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Checks if the block the sign is on is updated and drops the sign if so.

### CODE REVIEW

**Comment by PEMapModder** [comment]
Please do not add debug messages into the commits

**Comment by Falkirks** [comment]
Also if you want to debug use the debug method builtin to PocketMine, not `echo`.

**Comment by willowmaster66** [comment]
I believe Intyre fixed this in a commit to the 0.12 blocks and items branch. It has more code.

**Comment by thebigsmileXD** [comment]
@PEMapModder Oops, i'll update.
@Falkirks i don't even know why i have used echo().. i bet because i was on this file: https://github.com/alejandroliu/bad-plugins/blob/master/Mobsters/src/aliuly/mobsters/Main.php
@willowmaster66 Maybe less code is better ;)

**Comment by thebigsmileXD** [comment]
This update was dumb..

**Pull request closed without merging**
