### PR TITLE
Added ProjectileHitEntityEvent

### LINKED ISSUE #3596: ProjectileHitEvent enhancement
ProjectileHitEvent is triggered when a projectile collides with an entity or a block. The event should be enhanced such that plugins can easily know what entity or block is hit.

### PR DESCRIPTION
**Pull request by PEMapModder**
Resolves #3596

### CODE REVIEW

**Comment by PocketKiller** [comment]
:+1:

**Comment by robske110** [comment]
Lol Travis CI wants php7

**Comment by thebigsmileXD** [comment]
What about the ProjectileHitEvent itself? Still called?

**Comment by PEMapModder** [comment]
Called by projectile hitting a block.

**Comment by thebigsmileXD** [comment]
Closed? Why that, it works and its useful API

**Comment by PEMapModder** [comment]
Because the base branch is deleted.

**Pull request closed without merging**
