### PR TITLE
Fixed fallingsand bug

### PR DESCRIPTION
**Pull request by MinecrafterJPN**
Fixed bug
+ A chest will break when sand fall on the chest.

### CODE REVIEW

**Comment by PEMapModder** [comment]
Maybe using `(int)` is better than using `floor()`.

**Comment by Falkirks** [comment]
There is also a `round` method in `Vector3`.

**Comment by PEMapModder** [comment]
@Falkirks 

X => floor
Y => round
Z => floor

```
G G G
   X
G G G

G G G
```
Suppose bottom left corner is x.0,z.0, `X` would be placed outside if we use `round()`.

For the Y, it is in case the block fell a bit more than the ground, then it would get sucked into the ground. Assuming that the block won't fall more than 0.5 block in a tick, rounding Y is more suitable.

**Comment by MinecrafterJPN** [comment]
@PEMapModder Thank you

**Pull request closed without merging**
