### PR TITLE
Added constants related to armor parts!

### PR DESCRIPTION
**Pull request by Striker209MPE**
Easier for developpers :D

### CODE REVIEW

**Comment by Striker209MPE** [comment]
Nobody for ?

**Comment by PEMapModder** [comment]
What are the `CAP` `TUNIC` `PANTS` constants for?

**Comment by Striker209MPE** [comment]
It's for leather armor (if developers just remember the Leather part name :D)

**Comment by shoghicp** [comment]
You already have methods to get parts in the inventory objects.

**Pull request closed without merging**
