### PR TITLE
Fix sugarcane and cactus crash

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Just a question: could this happen on signs too?

@PEMapModder here is a clean PR

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
#3752 #3806

**Comment by samalero** [comment]
`elseif($type === Level::BLOCK_UPDATE_SCHEDULED){
			$this->getLevel()->useBreakOn($this);`

change it in both files on

`elseif($type === Level::BLOCK_UPDATE_SCHEDULED)
			$this->getLevel()->useBreakOn($this);`

**Comment by thebigsmileXD** [comment]
@samalero why that? its proper coding style..
```		}elseif($type === Level::BLOCK_UPDATE_SCHEDULED){```

**Comment by TheIcyStar** [comment]
something something [required code syntax?}(https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#code-syntax)

**Comment by Falkirks** [comment]
@samalero See http://stackoverflow.com/questions/691476/are-singleline-if-statements-or-if-statements-without-braces-bad-practice. When working with large projects which are maintained and consumed by many people, it is usually better to include braces.

**Comment by thebigsmileXD** [comment]
@Falkirks See what PM wants as formatting.

**Comment by samalero** [comment]
Just check the braces in these places. One bracket is not enough ...

**Comment by thebigsmileXD** [comment]
> bad practice

Okay. So coding correctly but have (you say so.. incorrect styling) is bad practice.. Using sleep() is bad practice. using print() as debug is bad practice. Calling PM api functions on async task is bad practice. But using {} even they are not needed is not bad practice..

**Comment by TheIcyStar** [comment]
This thread turned into a debate on what is and is not bad coding practice.

I urge you guys to stop trying to [decide on the color of the bike shed](https://en.wikipedia.org/wiki/Law_of_triviality) and discuss the main project at hand - this pull request

**Comment by thebigsmileXD** [comment]
The style doesnt matter anyways, PM can be glad that there are still people creating PRs.

**Comment by thebigsmileXD** [comment]
Created a new PR to clean this up.

**Pull request closed without merging**
