### PR TITLE
Remove unused parameter in Level::requestChunk

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by sekjun9878** [comment]
Sounds good. PHP doesn't check user-defined function parameters strictly so this should be BC compatible.

**Comment by SkygridRex** [comment]
I see preference for some users (like a PeMapModder)

**Comment by PEMapModder** [comment]
@SkygridRex please note that this is an issue tracker, not a forum.

**Comment by sekjun9878** [comment]
@SkygridRex Not really... Usually I just see some new PR on my GitHub feed, and respond to them so.. I'll look at the others when I have the chance.

**Comment by shoghicp** [comment]
This was an old parameter that was not removed waiting for the API change... But I guess it's ok to do it now

**Pull request merged**
