### PR TITLE
Fix for #3752

### PR DESCRIPTION
**Pull request by thebigsmileXD**
https://github.com/ImagicalCorp/ImagicalMine/commit/da15fe2ef0c90e88083fd2cfd378e1b23d3f8b78

### CODE REVIEW

**Comment by PocketKiller** [comment]
what's wrong with Travis these days?

**Comment by thebigsmileXD** [comment]
Wasn't the travis.yml updated by keithkfng? If he cloned the PocketMine one: that one is buggy

**Comment by PEMapModder** [comment]
wait, how does this have anything to do with @keithkfng?

**Comment by thebigsmileXD** [comment]
Whoops, haven't seen thats the official one

**Pull request closed without merging**
