### PR TITLE
Fixed hasPermission()

### PR DESCRIPTION
**Pull request by TahaTheHacker**
When you use hasPermission() when the player is offline (eg. you do it in PlayerPreLoginEvent) it crashes, but this fixes the crash but the error yeah.

### CODE REVIEW

**Comment by TahaTheHacker** [comment]
This fixes $player->kick, EssentialsPE, and some functions on the API.

**Comment by LouisBHirst** [comment]
omg if this works i <3 u

On Thu, Oct 15, 2015 at 10:42 AM, Taha_The_Hacker <notifications@github.com>
wrote:

> This fixes $player->kick, EssentialsPE, and some functions on the API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketMine/PocketMine-MP/pull/3603#issuecomment-148407466>
> .
>



-- 
Bart Hirst
(484) 802-4798
http://www.linkedin.com/in/louisbhirst

**Comment by TahaTheHacker** [comment]
@LouisBHirst I've Tested it, it works perfectly.

**Comment by MajikalPayton** [comment]
Don't log anything. Just return false.

**Comment by TahaTheHacker** [comment]
@MajikalPayton Oh forgot to stop the spams.

**Comment by 64FF00** [comment]
@TahaTheHacker
```PHP
if($this->perm === null)
    return false;

return $this->perm->hasPermission();
```

**Comment by Amircode09** [comment]
When Join Give random Amour

**Comment by sekjun9878** [comment]
@64FF00 That doesn't follow the coding standards, and not using brackets is a code smell. Also, a shorthand if would work better in that case.

**Pull request closed without merging**
