### PR TITLE
Create DaylightDetectorInverted.php

### PR DESCRIPTION
**Pull request by PocketServers**
Redstone item

### CODE REVIEW

**Comment by PEMapModder** [comment]
1. It appears that these are from ImagicalMine.
2. One commit per feature, not one commit per file. And one pull request for everything. Please. Stop spamming.

**Comment by Falkirks** [comment]
These branches have internal dependencies, there is no clear merging order. They would need to be rebased onto one branch before merging. As @PEMapModder you are being spammy and on behalf the 861 people who got notifications from these PRs, I ask you to stop it.

**Comment by KnownUnown** [comment]
^ +1

**Comment by BlackShadow1** [comment]
@Falkirks what's the problem for the LGPL?

**Comment by iksaku** [comment]
@Falkirks :+1:

**Pull request closed without merging**
