### PR TITLE
Basic 0.13 support

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by iJoshuaHD** [comment]
does thos fix the skin bug?

**Comment by PEMapModder** [comment]
I'm working on it

**Comment by PEMapModder** [comment]
Fixed.

**Comment by iJoshuaHD** [comment]
how about Chests and Inventory?

**Comment by iksaku** [comment]
Wow! Thanks @PEMapModder! Now going to get some more investigation with Wireshark :3 Hopefully committing soon :D

**Comment by PEMapModder** [comment]
@iJoshuaHD I was unable to reproduce any container-related bugs. However, there were bugs with trapdoors, which I believe to be from original PocketMine.

**Comment by HOSTMARCEL** [comment]
what are the current bugs with this version?

**Comment by PEMapModder** [comment]
I didn't notice any 0.13-related bugs with this version.

**Comment by HOSTMARCEL** [comment]
alrighty thanks, just 1 more question how can i download the latest myself to compile it?
i'm a bit noob when it comes to github, i end up downloading the official

**Comment by AryToNeX** [comment]
Am I the only one who does not see others' skins in 0.13.0?

**Comment by PEMapModder** [comment]
@AryToNeX according to my tests, this branch fixes skins. (I use Android)

**Comment by iksaku** [comment]
@AryToNeX @PEMapModder They also work to me (for now), I'm in iOS ;)

**Comment by AryToNeX** [comment]
@iksaku @PEMapModder It does not work to me... Maybe I'm doing something wrong... I only see my skin, but not others' skin.. So strange

**Comment by iksaku** [comment]
@AryToNeX There could be something wrong either in client's or server's side...

**Comment by iJoshuaHD** [comment]
@PEMapModder  ahhh, i see. thanks! :3

**Comment by PEMapModder** [comment]
Closed in the light of 2ea81710ad31d28dd934e7831a2419c8e70f77bd

**Pull request closed without merging**
