### PR TITLE
Update Block.php

### PR DESCRIPTION
**Pull request by Samueljh1**
Adds event caller to BlockActivateEvent (Pull request for BlockActivateEvent: https://github.com/PocketMine/PocketMine-MP/pull/3881)

### CODE REVIEW

**Comment by PEMapModder** [comment]
This pull request requires the dependency of another pull request, hence the pull request head branch should be based on the other pull request so as to make this pull request valid.

**Comment by dterweij** [comment]
is there still someone handling the pull requests? I think it is going to be a very messy place here :)

**Comment by Samueljh1** [comment]
@dterwejj Yeah.. Lol

**Comment by PEMapModder** [comment]
Please base this on #3882. This pull request is invalid until it can independently function correctly.

**Pull request closed without merging**
