### PR TITLE
Added Mob Heads

### PR DESCRIPTION
**Pull request by iksaku**

### CODE REVIEW

**Comment by s3r1alpari4h** [comment]
Why is this not merged lol

**Comment by iksaku** [comment]
Ping @PEMapModder @Intyre ... Should I update this to PHP7?

**Comment by PEMapModder** [comment]
Yes. For the while, this should be closed as it is outdated. You may create another pull request or request this one to be reopened when this is ready.

**Comment by iksaku** [comment]
I'm now updating this pull to PHP7... Should I open a new pull or you just "open" this one again to get the new commits?

**Pull request closed without merging**
