### PR TITLE
Fixed some typos in Anvil

### PR DESCRIPTION
**Pull request by alejandroliu**
Fixes some strange typos in the Anvil implementation.

### CODE REVIEW

**Comment by PEMapModder** [comment]
Skylight and light are different.

**Comment by shoghicp** [comment]
I've fixed several issues with your submission that did not follow the Contribution Guidelines. Following them is enforced.

**Comment by alejandroliu** [comment]
Sorry for not following the contribution Guidelines.

I will try to be more descriptive the next time.  If you are referring to the "PR: Bug Fix" label not being applied, I don't seem to have access to that.

Following this [article](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) the referred to options are not available to me.

**Comment by shoghicp** [comment]
The labels are applied by the moderators/contributors here, depending on the type of the submission.

**Pull request merged**
