### PR TITLE
Add support for 0.15.4

### PR DESCRIPTION
**Pull request by TheAppleGamer**

### CODE REVIEW

**Comment by extremeheat** [comment]
Based on your PR, there's been *absolutely* no protocol changes, am I right?

**Comment by TheAppleGamer** [comment]
Only one protocol change

**Comment by extremeheat** [comment]
Which is? Shouldn't your PR address the change then?

**Comment by dktapps** [comment]
Wooo, you guessed the magic number. Great. Now, what _actually_ changed? Version numbers don't get changed for no reason.

**Comment by jojoe77777** [comment]
> Version numbers don't get changed for no reason.

I think it may just be because of the new skin pack.

**Comment by dktapps** [comment]
@jojoe77777 I was referring to the protocol version, not the game version. I'll update my earlier comment

**Comment by jojoe77777** [comment]
@dktapps Yes, I was also referring to that. I was wondering what would happen if someone with a new skin could join a sever with older clients... The older clients wouldn't be able to render the skin properly, so it would need a protocol bump so that doesn't happen. There may also be another reason for the bump.

**Comment by extremeheat** [comment]
@jojoe77777 custom skins can already be used, so I don't really see what you're referring to here. Unless massive things changed with the skin rendering model, or how skins are transmitted, there would be no protocol-related changes.

**Comment by robske110** [comment]
Well the client wouldn't be able to render these skins in the old version

**Comment by dktapps** [comment]
@extremeheat is right. Thank you, you beat me to it.

**Pull request closed without merging**
