### PR TITLE
Implemented PluginErrorEvent

### PR DESCRIPTION
**Pull request by PEMapModder**
As described by @shoghicp in #2414

### CODE REVIEW

**Comment by PEMapModder** [comment]
Or should the events start from `ExceptionEvent` and not be limited to plugin-related exceptions?

**Comment by Falkirks** [comment]
:+1:

**Comment by shoghicp** [comment]
I'll review this in more detail once I get good internet at home, roaming sucks!

**Comment by thelucyclub** [comment]
:hankey: <- Hankey

**Comment by sekjun9878** [comment]
How about putting all the Error Events under pocketmine\events\plugin\error instead of just on pocketmine\events\plugins with everything else?

**Comment by jython234** [comment]
A little off topic, but why does travis seem to fail all the time?

**Comment by PEMapModder** [comment]
This pull request appears to be too obsolete.

**Pull request closed without merging**
