### PR TITLE
Implement Potion

### PR DESCRIPTION
**Pull request by Yosshi999**
todo:implement harming / healing potion

### CODE REVIEW

**Comment by SkygridRex** [comment]
Hace you test it?

**Comment by Yosshi999** [comment]
Ofcourse!

**Comment by jasonwynn10** [comment]
when will healt and damage be implemented?

**Comment by Yosshi999** [comment]
this is because the InstanceEffect has not been implemented yet. Look at pocketmine/entity/effect.php .

**Comment by dktapps** [comment]
> when will health and damage be implemented?

Answer: never. This repository is dead, haven't you finally realized?

**Comment by jasonwynn10** [comment]
I have known for a while, and eventually I plan on reviving it @dktapps

**Comment by dktapps** [comment]
That's some funny bullshit right there... put it off, or make another spoon.

**Comment by Yosshi999** [comment]
i think using genisys is the best answer.

**Comment by jasonwynn10** [comment]
@yosshi999 traitor

**Comment by jasonwynn10** [comment]
All I need to do is get admin access to the repo. I'll get in contact with @shoghicp I have all day every day to work on the repo for the next few months. That should be enough time to get some work done.

**Comment by dktapps** [comment]
ROFL you're so funny 😂😂😂😂😂

**Comment by SOF3** [comment]
This is not a forum.

**Comment by thebigsmileXD** [comment]
Back to toppic. Its not a forum here, and note a jokeshow.
> Implement Potion

**Comment by dktapps** [comment]
This is obsoleted by changes in the PMMP repository.

**Pull request closed without merging**
