### PR TITLE
[php7-0.14] Update BaseLevelProvider.php

### PR DESCRIPTION
**Pull request by 64FF00**
**[02-07-2016] Re-opened the PR again. I messed up the branches in my fork xD**

Not sure why but it seems like the NBT thingy keeps writing the integer seed in a string format...

### CODE REVIEW

**Comment by PEMapModder** [comment]
@64FF00 have you tried a `var_dump` on it to confirm that the tag is indeed returning a string representation of a number?

**Comment by PEMapModder** [comment]
I think this is OK to merge.

**Comment by 64FF00** [comment]
@PEMapModder @PEMapModder Unfortunately it doesn't. I know it's just a workaround, but I'm sure there's something wrong with the NBT tag parser.

**EDIT**: *Is this correct @PEMapModder*
```
[1] Server : Server::loadLevel(string $name);
[2] Level : Level::__construct(Server $server, string $name, string $path, string $provider); 
[3] LevelProvider : LevelProvider::_construct(Level $level, string $path);
[4] LevelProvider : LevelProvider->levelData = (CompoundTag) new NBT(NBT::BIG_ENDIAN)::getData();
[5] Server : Level::initLevel();
[6] Level : Generator::init(Level $level, new Random(Level::getSeed()));
[7] Level : Level::getSeed();
[8] Level : LevelProvider::getSeed();
[9] LevelProvider : return LevelProvider->levelData["RandomSeed"];
[10] LevelProvider : *returns a string RandomSeed value instead of an Integer seed*
```

**Comment by 64FF00** [comment]
@PEMapModder ^^^

**Pull request merged**
