### PR TITLE
Disallow registration of events without handlerList

### PR DESCRIPTION
**Pull request by PEMapModder**
Fixes another issue mentioned in #3330

### CODE REVIEW

**Comment by TigerHix** [comment]
Good one. It is quite common to register events without `handlerList`, such as `EntityDamageByEntityEvent` which extends `EntityDamageEvent`. Strangely and confusing though, `PlayerDeathEvent` that extends `EntityDeathEvent` has the `handlerList` field.

**Comment by sekjun9878** [comment]
Could you give me an example of what this is supposed to fix? #3330 doesn't give any examples and I don't deal with PM enough to know what problems this causes.

**Comment by sekjun9878** [comment]
Just to clarify, this is a purely syntactic sugar change. This is estimated to break some plugins that incorrectly utilise some inherited Events, but that is an incorrect usage and not covered by the BC guarantee. 

This check makes sure that there are no type hint errors by making it impossible to Events that are a child of another event, but don't have its own $handlerList. 

@PEMapModder Add a nice little message and I'll merge this right away

**Comment by sekjun9878** [comment]
It's been merged!

**Pull request merged**
