### PR TITLE
Stonecutter recipes

### PR DESCRIPTION
**Pull request by willowmaster66**
Updated blocks/items with constants and added new block/items needed for some of the recipes.

Then removed the shapeless stone cutter recipes and added the shaped recipes. Tried to create a tabular array for the recipes with only one type of ingredient.

### CODE REVIEW

**Comment by shoghicp** [comment]
Good work, I'll review this tomorrow.

**Comment by TahaTheHacker** [comment]
Awesome :+1: :+1:

**Comment by D3thw0lf** [comment]
NICE! :+1:

**Comment by Galang23** [comment]
Love this change!

**Comment by SkygridRex** [comment]
Lol! Why shogui don't merge this?

**Comment by willowmaster66** [comment]
@SkygridRex: I think he has a lot on his mind with php7. Just be patient and let him finish it. This code won't run away. :-)

**Comment by willowmaster66** [comment]
I have been thinking about moving the recipes to the class where the result of the recipe is of the type of the class. You can call a function like Stone::getRecipes() which will return all the recipes for Stone. That might be cleaner for the CraftingManger class.

What do you think?

**Comment by shoghicp** [comment]
Let's not make stones (or other items) know about recipes :)

It's ok to have a way to do that on the recipe manager, but you can have blocks without recipes (it's a separated system)

**Pull request merged**
