### PR TITLE
Show Travis-CI Build Status on README.md.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
For Github visitors, many projects shows its project build status in README.md.
It would be nice if PocketMine-MP shows Travis-CI build status, too.
Here is the sample layout in this PR branch.

https://github.com/dongjoon-hyun/PocketMine-MP/tree/show_travis_build_status

Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>

### CODE REVIEW

**Comment by PEMapModder** [comment]
We probably need to update .travis.yml before merging this.

**Comment by 64FF00** [comment]
@PEMapModder Agreed

**Comment by dongjoon-hyun** [comment]
Oh, today master branch became PHP7. Great.

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by PEMapModder** [comment]
I guess this is OK.

**Comment by dongjoon-hyun** [comment]
Thank you again, @PEMapModder .

**Pull request merged**
