### PR TITLE
Added Mob Heads

### PR DESCRIPTION
**Pull request by iksaku**
* Fixed duplicated items in JSON file

### CODE REVIEW

**Comment by iksaku** [comment]
Rebased a little fix...

**Comment by robske110** [comment]
?

**Comment by iksaku** [comment]
@robske110 Harming? I don't think so...

**Comment by robske110** [comment]
Where did you read "Harming"?

**Comment by iksaku** [comment]
This is not a forum, argue in Twitter... And I'm pointing out that this is not `harming`, I do not have interest in updating any other code...

**Comment by PrimusLV** [comment]
Jorge, is that you or that's real @PEMapModder ?

**Comment by dktapps** [comment]
I blame @PEMapModder for not testing this PR properly. :P

**Comment by jojoe77777** [comment]
@dktapps you should be blaming iksaku, PEMapModder wasn't involved :P

**Comment by jojoe77777** [comment]
(you do realise it was iksaku?)

**Comment by Falkirks** [comment]
@dktapps @jojoe77777 This is not a forum. 1168 get notified when you reply here.

**Comment by dktapps** [comment]
@jojoe77777 yeah, but look who merged it... ;P

**Pull request merged**
