### PR TITLE
Added Taiga biomes

### PR DESCRIPTION
**Pull request by Muqsit**
Hope this pr gets merged. I've also tested it by myself. There were no console error produced. There were no errors at all, no lag, chunk loading speed wasn't affected at all. It's all good :)

### CODE REVIEW

**Comment by Muqsit** [comment]
@PEMapModder notice me senpai :3

**Comment by PEMapModder** [comment]
@Muqsit pull requests will be reviewed when it is the right time. Please do not rush the developers.

**Comment by Muqsit** [comment]
@PEMapModder oh, sawryy~!

**Comment by robske110** [comment]
Why still NO Merge? -_-

**Comment by thebigsmileXD** [comment]
+			Block::get(Block::MOSS_STONE, 0),
 +			Block::get(Block::MOSS_STONE, 0),
 +			Block::get(Block::MOSS_STONE, 0),

Why did you add 3 layers of mossy stone below the dirt

**Comment by dktapps** [comment]
There are complaints with this PR that cannot be resolved because the original branch&repo has been deleted.

**Pull request closed without merging**
