### PR TITLE
Add basic MOB support.

### PR DESCRIPTION
**Pull request by gimilii**
Hi,

    First of all thank you for creating the pocketmine server code. I have made some pocket mine changes to add basic mob support.  I am new to github, so I hope I am doing this correctly.

I have attempted to implement basic MOB support.  At this point all monsters move / attack the same way, and I didn't add support for explosion, etc.  But the MOBS do follow once a player is detected and
they do attack.  I also added a bunch of mob commands:

[17:14:12] [Server thread/INFO]: Supported mobs commands
[17:14:12] [Server thread/INFO]: mobs sleep - Put all mobs to sleep
[17:14:12] [Server thread/INFO]: mobs wakeup - Wake up all mobs
[17:14:12] [Server thread/INFO]: mobs kill - Kill all mobs
[17:14:12] [Server thread/INFO]: mobs status - Show mobs status
[17:14:12] [Server thread/INFO]: mobs types - List supported mob types
[17:14:12] [Server thread/INFO]: mobs speed [All, MobType] speedValue - Set mob speed
[17:14:12] [Server thread/INFO]: mobs attack [All, MobType] attackValue - Set mob attack damage
[17:14:12] [Server thread/INFO]: mobs health [All, MobType] healthValue - Set mob health
[17:14:12] [Server thread/INFO]: mobs proximity [All, MobType] healthValue - Set mob proximity 

The mobs are still created using the spawn eggs at the moment, but I thought of also adding command line for that with coordinates, etc. 

You can contact me at darinf@yahoo.com

I also attempted to add rail / mine cart support several months ago.  I have the rail working and the mine cart working on the rail, but the one thing I couldn't figure out is how to get the player to actually get into the cart.  So instead the rider sort of just runs next to the cart.  I tried using the SetEntityLinkPacket, but was unable to get it to work.  I am not sure if you would know how to fix that.  If I could fix that, the rest of the support I think is there.

### CODE REVIEW

**Comment by robske110** [comment]
Why Travis Failed?

**Comment by gimilii** [comment]
Maybe because Travis didn't have access to my github account?  I am not sure I am new to GitHub.  I have authorized Travis to my GitHub account now.  Is there a way to try to kick off the build again?

**Comment by Intyre** [comment]
Travis doesn't like it when you remove important files. 
```
src/pocketmine/lang/locale
src/raklib
src/spl
```

**Comment by gimilii** [comment]
When I forked from the Master I didn't get those files.  Maybe I did the fork wrong?  I chose fork from master and it created me a copy in my account, but it only have src/pocketmine, not src/raklib, src/spl or tests/TesterPlugin.  I notice when I look at those folders on github they look different then src/pocketmine.

**Comment by gimilii** [comment]
It looks like TesterPlugin is a link to PocketMine/TesterPlugin and rakLib is a link to PocketMine/Raklib and spl is a link to PocketMine/SPL.  I just forked PocketMine/Pocketmine-MP and it looks like it didn't copy these links.  Do I need to fork those projects as well?

**Comment by Intyre** [comment]
Clone with ``git clone --recursive``
or ``git submodule update --init --recursive`` when you already cloned it.

Prevent it by manually adding files with ``git add <filename>``

**Pull request closed without merging**
