### PR TITLE
Added some flowers

### PR DESCRIPTION
**Pull request by matcracker**
Added Blue Orchid, Allium, Azure Bluet, Red Tulip, Orange Tulip, White Tulip, Pink Tulip, Oxeye Daisy.

### CODE REVIEW

**Comment by matcracker** [comment]
Works :dancer: http://imgur.com/lUhobBB

**Comment by LDX-MCPE** [comment]
:+1:

**Comment by matcracker** [comment]
:smile:

**Comment by matcracker** [comment]
I press the wrong button :joy:

**Comment by GrandFelix** [comment]
Rails still cant be used...

**Comment by matcracker** [comment]
@GrandFelix the title say flowers not rails :smile:

**Comment by sekjun9878** [comment]
Merged with 388f5c2c91219120dedc8d91b0afa79d1a30fe13. Thank you!

**Comment by shoghicp** [comment]
@sekjun9878 please revert this change. Breaks backwards compatibility and needs other stuff, but I'm away now

**Comment by sekjun9878** [comment]
@shoghicp The BC can be fixed by https://github.com/PocketMine/PocketMine-MP/compare/master...sekjun9878:fix-flowers-bc which adds stub classes, and the additional stuff can be added with further commits :)

**Pull request closed without merging**
