### PR TITLE
Update BaseLevelProvider.php (php7-0.14)

### PR DESCRIPTION
**Pull request by 64FF00**
Not sure why but it seems like the NBT thingy keeps writing the integer seed in a string format...

### CODE REVIEW

**Comment by PocketKiller** [comment]
travis failed...

**Comment by xpyctum** [comment]
@PocketKiller
[CRITICAL] You must use PHP >= 7.0
[CRITICAL] Please use the installer provided on the homepage.

**Comment by 64FF00** [comment]
@PocketKiller https://travis-ci.org/PocketMine/PocketMine-MP/builds/107432925 ```
[CRITICAL] You must use PHP >= 7.0
[CRITICAL] Please use the installer provided on the homepage.
```

@xpyctum :+1:

**Comment by 64FF00** [comment]
Imgur

**Comment by PEMapModder** [comment]
Does this fix the issue of returning string? (And are you sure that it really does?) According to [php.net](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration), if strict typing is enabled, a `TypeError` would be thrown if the return value is not an int.

**Comment by 64FF00** [comment]
@PEMapModder Unfortunately it doesn't. I know it's just a workaround for it, but I'm sure there's something wrong with the nbt tag parsing...

**Pull request closed without merging**
