### PR TITLE
#3433 add check for Compound::$item

### PR DESCRIPTION
**Pull request by ecoron**
add missing check if namedTag->Item exists
should solve the issue #3433

### CODE REVIEW

**Comment by shoghicp** [comment]
If that doesn't exist the item is invalid and should be removed,

also your commit changed formatting.

**Comment by PEMapModder** [comment]
Trailing spaces should just be removed :cry: many IDEs do that

**Comment by rock2rap** [comment]
How to fix it?

**Comment by ecoron** [comment]
it's more to prevent the crashes if $this->namedTag->Item wasn't proper initialized.
i think the real issue is the missing initialization, but it's not clear where to do.
and yes my IDE removes trailing spaces automaticly. normaly it replace also tabs with 4 spaces ;)

**Comment by shoghicp** [comment]
This is already fixed in php7 branch

**Pull request closed without merging**
