### PR TITLE
Skin bug fix

### PR DESCRIPTION
**Pull request by 0929hitoshi**
It was fixed a bug that skin of the player(human) is not reflected

### CODE REVIEW

**Comment by PEMapModder** [comment]
Tested?

**Comment by HmHmmHm** [comment]
what skin bug?

**Comment by PocketKiller** [comment]
@HmHmmHm
```
Steve [Ip:port] logged out due to Invalid skin!

**Comment by 0929hitoshi** [comment]
@PEMapModder yes

**Comment by PEMapModder** [comment]
@PocketKiller that's totally irrelevant.

**Comment by HmHmmHm** [comment]
@PocketKiller that's not 0.13.0 client problem?

**Comment by iksaku** [comment]
Can you tell us which steps are needed to reproduce the error you're reporting?

**Comment by thebigsmileXD** [comment]
0.14 is out, the bugs got less.

**Comment by PEMapModder** [comment]
As this pull request is not supported with sufficient elaboration, this is being closed.

**Pull request closed without merging**
