### PR TITLE
Fixed sugarcane and cacti crash when too high #3752

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Wow.. finally got this fixed.
When you placed more than 100 cacti above each other (or sugarcane) they
let the server crash due to overflow call.
Thanks @PEMapModder

### CODE REVIEW

**Comment by PEMapModder** [comment]
Confirmed that this works?

**Comment by thebigsmileXD** [comment]
Oh yea. Placed sand on bedrock layer and stacked it up to build limit. Then broke the sand and the items fell.

**Comment by PEMapModder** [comment]
The head tree is contaminated with irrelevant commits. Please open a pull request without irrelevant commits.

**Comment by thebigsmileXD** [comment]
I will

**Comment by thebigsmileXD** [comment]
Oh, i see. This is just messed up because another pr is in the same branch.

**Comment by SOF3** [comment]
See also: https://en.wikipedia.org/wiki/Tail_call

**Pull request closed without merging**
