### PR TITLE
Added classes for items with constants

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
Didn't notice I'm duplicating the IDs.

**Comment by willowmaster66** [comment]
I'm not sure a minecart is an item. Maybe a tile or a block.

**Comment by PEMapModder** [comment]
@willowmaster66 the Minecart is not a block. It is an entity. But when you have crafted a Minecart in your inventory, it is a Minecart.

**Comment by willowmaster66** [comment]
@PEMapModder: A minecart is also an item in the inventory, but it is more. It is a moving "chest". It contains players. So it can not be purely an item as you have done in this case.

**Comment by PEMapModder** [comment]
@willowmaster66 yes, but a minecart item is only used as an Item in this class. For the minecart entity, it should be implemented in another class just like arrow.

**Pull request closed without merging**
