### PR TITLE
Implemented redstone

### PR DESCRIPTION
**Pull request by PEMapModder**
This is not done yet, but it is still stable enough to be merged. 

Current issues at LegendOfMCPE/PocketMine-MP#1

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
And why do have you added a "," in zhe arrays?

**Comment by PEMapModder** [comment]
@thebigsmileXD sorry, blame my PhpStorm auto reformat :P

**Comment by thebigsmileXD** [comment]
:P that can happen when you use autoformat ^^

**Comment by PEMapModder** [comment]
@thebigsmileXD I use autoformat on my own code, because I type `$a=$b.$c;` rather than `$a = $b . $c;` when I code, and then autoformat it to add the spaces. more efficient coding this way.

**Comment by thebigsmileXD** [comment]
yup. Same for me.. but it often messes up things

**Comment by SkygridRex** [comment]
@PEMapModder Why not use isPowered?

**Comment by PEMapModder** [comment]
@SkygridRex see LegendOfMCPE/PocketMine-MP#2 - our understanding of redstone mechanics in Minecraft is that there are different levels of power as well as different types of charges.

**Comment by PEMapModder** [comment]
Closed for incorrect base. Will open another PR when the branch looks a bit nicer.

**Pull request closed without merging**
